################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'washingmachine'

    ################################################
    ## Group
    ################################################

    group.washing_machine:
      <<: *customize
      friendly_name: "Washing Machine"
      icon: mdi:washing-machine

    ################################################
    ## Sensor
    ################################################
    sensor.washingmachine_power:
      <<: *customize
      icon: mdi:flash
    sensor.washing_machine_status:
      <<: *customize
      icon: mdi:washing-machine


input_select:
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
    initial: Idle

sensor:
  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'

group:
  washing_machine:
    entities:
      - sensor.washingmachine_power
      - sensor.washing_machine_status
      - sensor.washingmachine_energy

automation:
  # When power is detected, and the washing machine is not in 
  # the Running state, change the status of the washing machine
  # to Running. 
  # The status check will ensure we don't try to put the state 
  # to Running each time the power level changes, and we're already
  # in the Running state.
   
  - alias: Set washing machine active when power detected
    trigger:
      - platform: numeric_state
        entity_id: sensor.washingmachine_power
        above: 10
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Idle
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Clean
        - condition: state
          entity_id: sensor.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Running
   
  # When the power drops, move the state of the washing machine to 
  # Finishing.
   
  - alias: Set washing machine finished when power drops
    trigger:
      - platform: numeric_state
        entity_id: sensor.washingmachine_power
        below: 4
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Running
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Finishing
   
  # Wait 8 minutes for us to be in the Finishing state before we
  # decide the washing machine has finished. This way, if the 
  # washing machine is in between cycles and the power drops, we 
  # won't mark the washing machine cycle as finished too early.
   
  - alias: Set washing machine clean after timeout
    trigger:
      - platform: state
        entity_id: input_select.washing_machine_status
        to: Finishing
        for:
          minutes: 8
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Finishing
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean
  

  # When power is off, reset the status back to
  # idle, so we don't spam people that the washing machine has 
  # finished, and someone has already emptied it
  - alias: Set washing machine to idle when power is off
    trigger:
      - platform: numeric_state
        entity_id: sensor.washingmachine_power
        below: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state: Clean
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Idle
   